// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9wrbG5gt-bwyV1qBbRqBHWeBLcAoSQWA',
    appId: '1:789834919437:web:609cccf116350cee016f44',
    messagingSenderId: '789834919437',
    projectId: 'random-itinerary',
    authDomain: 'random-itinerary.firebaseapp.com',
    storageBucket: 'random-itinerary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjFunE1c8u_W2AbIeJd6E1jvG1QxHsDeI',
    appId: '1:789834919437:android:0bf8ecc052749f62016f44',
    messagingSenderId: '789834919437',
    projectId: 'random-itinerary',
    storageBucket: 'random-itinerary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxxtR6hZRNsdgX3oK2Ou3WM-YshcO2F3M',
    appId: '1:789834919437:ios:ef702b3324e53f09016f44',
    messagingSenderId: '789834919437',
    projectId: 'random-itinerary',
    storageBucket: 'random-itinerary.appspot.com',
    iosClientId: '789834919437-3s7i5qssrf4qdg89krfun1cqv9nuaef8.apps.googleusercontent.com',
    iosBundleId: 'com.example.randomIternerary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxxtR6hZRNsdgX3oK2Ou3WM-YshcO2F3M',
    appId: '1:789834919437:ios:ef702b3324e53f09016f44',
    messagingSenderId: '789834919437',
    projectId: 'random-itinerary',
    storageBucket: 'random-itinerary.appspot.com',
    iosClientId: '789834919437-3s7i5qssrf4qdg89krfun1cqv9nuaef8.apps.googleusercontent.com',
    iosBundleId: 'com.example.randomIternerary',
  );
}
